return {
	["--"]  = { precedence = 16},
	["++"]  = { precedence = 16},
	['(']   = { precedence = 16},
	['[']   = { precedence = 16},
	['.']   = { precedence = 16},
	["**"]  = { precedence = 14, rightAssociative = true},
	['*']   = { precedence = 13},
	['/']   = { precedence = 13},
	['%']   = { precedence = 13},
	['+']   = { precedence = 12},
	['-']   = { precedence = 12},
	[".."]  = { precedence = 11, rightAssociative = true},
	["<<"]  = { precedence = 10},
	[">>"]  = { precedence = 10},
	["<<<"] = { precedence = 10},
	[">>>"] = { precedence = 10},
	['<']   = { precedence = 9},
	['>']   = { precedence = 9},
	["<="]  = { precedence = 9},
	[">="]  = { precedence = 9},
	["=="]  = { precedence = 8},
	["!="]  = { precedence = 8},
	['&']   = { precedence = 7},
	['^']   = { precedence = 6},
	['|']   = { precedence = 5},
	["&&"]  = { precedence = 4},
	["^^"]  = { precedence = 3},
	["||"]  = { precedence = 2},
	['?']   = { precedence = 1, rightAssociative = true}
}
